

INSERT IGNORE INTO `permission` (`id`, `name`, `code`, `description`) VALUES
(NULL, 'Permission add', 'perm_act', 'perm_act'),
(NULL, 'usrgrp_act', 'usrgrp_act', 'usrgrp_act'),
(NULL, 'ad_prmsn_to_grp', 'ad_prmsn_to_grp'),
(NULL, 'usr_edt', 'usr_edt', ''),
(NULL, 'assn_clg_cntr', 'assn_clg_cntr', ''),
(NULL, 'rmv_usr', 'rmv_usr', ''),
(NULL, 'assn_drctr', 'assn_drctr', ''),
(NULL, 'ad_usr_to_grp', 'ad_usr_to_grp', ''),
(NULL, 'perm_act', 'perm_act', 'perm_act'),
(NULL, 'Manage board members', 'mng_brd_mbr', 'Manage board members'),
(NULL, 'View main dashboard', 'view_dashboard', ''),
(NULL, 'View own submission', 'vw_own_sub', ''),
(NULL, 'View all submissions', 'vw_all_sub', ''),
(NULL, 'View own co authorship', 'vw_own_mmbr', ''),
(NULL, 'View my assigned', 'vw_own_assign', ''),
(NULL, 'View granted researches', 'vw_gntd_rsrch', ''),
(NULL, 'View all publications', 'vw_all_pub', ''),
(NULL, 'View IRB dashboard', 'vw_irb_dbrd', ''),
(NULL, 'View IRB requests', 'vw_irb_rqst', ''),
(NULL, 'View all IRB review assignments ', 'vw_all_irb_assgn', ''),
(NULL, 'View Board members ', 'mng_brd_mmbr', ''),
(NULL, 'manage Board meeting ', 'brd_mtng', ''),
(NULL, 'manage Project Type ', 'mng_irb_pr_typ', ''),
(NULL, 'manage application Type ', 'mng_irb_app_typ', ''),
(NULL, 'manage Attachment Type ', 'mng_irb_atch_typ', ''),
(NULL, 'manage Research Subject Category ', 'mng_irb_rsub_cat', ''),
(NULL, 'manage Research Subject ', 'mng_irb_rsub', ''),
(NULL, 'manage Guideline attachemnts ', 'mng_irb_guid_atc', ''),
(NULL, 'Call for proposal list ', 'vw_cll_fr_prop', ''),
(NULL, 'Call for training list ', 'vw_cll_fr_trn', ''),
(NULL, 'view scholarships ', 'vw_schps', ''),
(NULL, 'view user list', 'vw_usr', ''),
(NULL, 'view user group list', 'vw_usr_grp', ''),
(NULL, 'view permission list', 'vw_perm', ''),
(NULL, 'view colleges list', 'vw_clg', ''),
(NULL, 'view director office list', 'vw_drtr_offc', ''),
(NULL, 'view Department', 'vw_dept', ''),
(NULL, 'view Directorate office', 'vw_dir_off', ''),
(NULL, 'view announcement', 'vw_annc', ''),
(NULL, 'view user feedback', 'vw_usr_fdbc', ''),
(NULL, 'view Service tree', 'vw_srv_tr', ''),
(NULL, 'view Setting tree', 'vw_stng_tree', ''),
(NULL, 'view Attachment type', 'vw_atch_typ', ''),
(NULL, 'view Site settings', 'vw_st_stng', ''),
(NULL, 'view backup settings', 'vw_bc_stng', ''),
(NULL, 'view general settings', 'vw_gn_stng', ''),
(NULL, 'view academic year', 'vw_ac_yr', ''),
(NULL, 'view Submission budget  category', 'vw_sb_bdgt_cat', ''),
(NULL, 'view Evaluation form option', 'vw_ev_frm_o', ''),
(NULL, 'view Evaluation form', 'vw_ev_frm', ''),
(NULL, 'view User prefix titles', 'vw_prf_ttl', ''),
(NULL, 'view Training type', 'vw_tr_typ', ''),
(NULL, 'view Subscription', 'vw_sbsc', ''),
(NULL, 'view Email messages', 'vw_em_msg', ''),
(NULL, 'Reports nav tree', 'rprts_nv_tr', ''),
(NULL, 'View Application submission Report', 'vw_app_sb_rp', ''),
(NULL, 'Create call for proposal', 'modify_call_pr', ''),
(NULL, 'Manage research reports', 'mng_rprts', ''),
 ;
