<?php
namespace App\Utils;

class Constants{

    //roles
     const ROLE_ADMIN="ROLE_ADMIN";
     const  PRESIDENT= "ROLE_PRESIDENT";
     const  VICE_PRESIDENT= "ROLE_VICEPRESIDENT";
     const  ROLE_DIRECTORATE= "ROLE_DIRECTORATE";
     const  ROLE_COLLEGECOORDINATOR= "ROLE_COLLEGECOORDINATOR";
     const  ROLE_WORK_UNIT= "ROLE_WORKUNIT";
     const  ROLE_REVIEWER= "ROLE_REVIEWER";
     
     const  SUBMISSION_STATUS_DECLINED= 1;
     const  SUBMISSION_STATUS_ACCEPTED_WITH_MAJOR_REVISION= 2;
     const  SUBMISSION_STATUS_ACCEPTED_WITH_MINOR_REVISION= 3;
     const  SUBMISSION_STATUS_ACCEPTED= 4;
         

     //email keys
     const EMAIL_KEY_SUBMISSION_ACKNOWLEDGEMENT="SUBMISSION_SUCCESS";


}